language: python
sudo: required
services:
  - docker

env:
  global:
    - IMAGE_NAME="luigid"
    - CONTAINER_NAME="luigid"
    - REPOSITORY="public.ecr.aws/macinv"
    - secure: "bhpVY74Eb4PyWETvo0I5oEIvS5WmIsbzbWj9QIgmarRY2Y5enkCltzm5rNX0D4wY5UYBzVTWJfe0rBbMT25rHh3X2UxFjr6XhqqqDCvFp0kQvuah0py96ni5knLny/NWnggPvmSzibx9BJa6y42xz8nmmG6fHBwmHTvZiI9M5RnSYIeZesZtqRc4EZpi+aH2trkAw/pLjjPAhZyzZv+yPXKecM8+g+5lWyegha9Dn31/tYzc16NeOq3/b/xPCZp+7SMsD5qoxnCGwtTqBoFdJQipsx43C+/2XXMjLNxSHS0yW/omyi9rc+hDCYHi5a7WG8IDdkzZ6nF54SJsZ/sgmo0Duiiwc5eDaTbfRVD9eo4g1gMijT1vjWcPg6q5DolMQ0ElpULXi0bmxVqV3DP0QOiKsX42N7NAko39jLaDVzeMAnfU1cHgDY+3uS7uM2uy8EkKzjgqzjHao71cBnIpT4aCMxQKFlrRPxj8DpSFQih4u/V0TAmUVWbCYKIJuCOr684I8+A/4Q9bGwGN0iA/a9bn+mbn7mlmp1Lyb5pNKVIwiMR70svpvhE/i5+OwBSQUMI47zx2xFx2XSMMT0CeSJf0nZ4npkTUNSZ0QZOqxMIQgvwi19Ixud5XPRrehG/fSoEDjfwUTqT8wKv+3B34TWalfbsoTul5+/OkQQpp2AI="

before_install:
  - openssl aes-256-cbc -K $encrypted_4f5dd6dc2a00_key -iv $encrypted_4f5dd6dc2a00_iv -in repository_password.enc -out repository_password -d

script:
  - travis_retry bash test_docker.sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master

notifications:
  email: true
  secure: "UxJZDq4IPtnkS2uLLiQUoG1uC6dnMppaVWGAQJvBmeYYIXBs40g1ghbnH+oa+3bPR2hUqxKB97dBAk4C0ZV8eTWDoIy5aNHZYHF/qmvMCukq+uN633Ght7g9b3h80VfNl12O0GQRBAxPVatYLFVcBRLsdc/T0lyLPyAn5KfQkNpJ40KmahdDK2P4K59Q6FFd8LpyVApIdrLc1kYHdfTzBSjrqMQy8TEq3BNxbrPNsYwpDpWzD6icTDxsrr0xhi8KS0bGcseA2+mu6Juk9TQdg0dNTqx/CVHcCt4eFOFxjWoH4F5Rz+rMlPAyoFYr/5i3oYAb2Cc3wdCC68izm3UgUaB7e1B53Icq8I08memEJ5NGJh1+aZEwV95F3gyGREw7X6Bb4emzR0kK6m/XKImLBOKPxuFyG0WhoAJogP+sI2+3WwwSgrwiP7vAVbdiwTdP9966VXwdOvNBSHKurE3mt1jKc/tEXDZU8FjRx2h0bmtylLgDP8maLMbOdSGkhd/uuxWfpa9Mbpyg60Ier1ffExeaOJbqy4JCRXarLMuOtd2B0f8ehPXzTfjW9ZnJf6P7Tb2pxPctXzLGlXwMMalgdGaxOcf1mz2rh+04EcDgC1SR1U6qSkiyGjHdKl1FVBIZnIUzUPnUPAAxTkEbjz2nDhOm6Ueioeu+bf0il79PCJs="
