language: python

sudo: required

services:
    - docker
env:
    global:
        - CONTAINER_NAME=travis_test_image
        - IMAGE_NAME=luigid:$TRAVIS_BRANCH
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_REGISTRY=536536802960.dkr.ecr

script:
    - travis_retry bash test_docker.sh

after_success:
    if: env(TRAVIS_BRANCH) = master OR env(TRAVIS_BRANCH)= dev
        - cp configs/.boto .
        - eval $(aws ecr get-login --region us-east-1 --no-include-email)
        - docker tag $IMAGE_NAME $AWS_REGISTRY.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME
        - docker push $AWS_REGISTRY.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME

notifications:
    email: true
    secure: UxJZDq4IPtnkS2uLLiQUoG1uC6dnMppaVWGAQJvBmeYYIXBs40g1ghbnH+oa+3bPR2hUqxKB97dBAk4C0ZV8eTWDoIy5aNHZYHF/qmvMCukq+uN633Ght7g9b3h80VfNl12O0GQRBAxPVatYLFVcBRLsdc/T0lyLPyAn5KfQkNpJ40KmahdDK2P4K59Q6FFd8LpyVApIdrLc1kYHdfTzBSjrqMQy8TEq3BNxbrPNsYwpDpWzD6icTDxsrr0xhi8KS0bGcseA2+mu6Juk9TQdg0dNTqx/CVHcCt4eFOFxjWoH4F5Rz+rMlPAyoFYr/5i3oYAb2Cc3wdCC68izm3UgUaB7e1B53Icq8I08memEJ5NGJh1+aZEwV95F3gyGREw7X6Bb4emzR0kK6m/XKImLBOKPxuFyG0WhoAJogP+sI2+3WwwSgrwiP7vAVbdiwTdP9966VXwdOvNBSHKurE3mt1jKc/tEXDZU8FjRx2h0bmtylLgDP8maLMbOdSGkhd/uuxWfpa9Mbpyg60Ier1ffExeaOJbqy4JCRXarLMuOtd2B0f8ehPXzTfjW9ZnJf6P7Tb2pxPctXzLGlXwMMalgdGaxOcf1mz2rh+04EcDgC1SR1U6qSkiyGjHdKl1FVBIZnIUzUPnUPAAxTkEbjz2nDhOm6Ueioeu+bf0il79PCJs=
